package it.unibo.goldhunt.engine.api;

/**
 * Represents the outcome of a reveal action performed on the board.
 * 
 * A {@code RevealResult} encapsulates whether the reveal operation
 * produced a change, the effect generated by the action, and the
 * updated level state after the reveal
 * 
 * @param changed indicates whther the board state was modified
 * @param effect the {@link ActionEffect} generated by the reveal action
 * @param newLevelState the resulting {@link LevelState} after the reveal
 */
public record RevealResult(
    boolean changed,
    ActionEffect effect,
    LevelState newLevelState
) { }
